#include <iostream>
#include <cstdio>
#include <sstream>

#include "FTB.hpp"

namespace FileToByte {
	std::string Convert(std::string Path, std::string VarName) {
		if (Path.empty() || VarName.empty())
			return "Path or variable name is empty";

		FILE* file = fopen(Path.c_str(), "rb");

		if (file == NULL)
			return "The path provided does not exist.";

		fseek(file, 0, SEEK_END);
		int length = ftell(file);
		rewind(file);
		unsigned char* buffer = new unsigned char[length];
		fread(buffer, 1, length, file);
		fclose(file);
		
		std::stringstream ss;
		ss << "#pragma once\n\n";
		ss << "/*\n";
		ss << " *\tGenerated by File To Byte\n";
		ss << " *\thttps://github.com/JerimiahOfficial/FileToByte\n";
		ss << " */\n\n";
		ss << "static const unsigned int " << VarName << "[/*" << length << "*/] = {\n";

		for (int i = 0; i < length; i++) {
			ss << "\t0x" << std::hex << (int)buffer[i];

			if (i != length - 1)
				ss << ", ";
			
			if ((i + 1) % 16 == 0 && i != 0 && i != length - 1)
				ss << "\n";
		}

		ss << "\n};";

		delete[] buffer;
		return ss.str();
	}
}
