/*
  MIT License

  Copyright (c) 2023 Jerimiah

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
*/

#include "../source/FTB.hpp"

#include <format>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <vector>

namespace FileToByte {

std::string Convert(const std::string &Path, const std::string &VarName) {
  // Read file
  std::ifstream file(Path, std::ios::binary);

  if (!file.is_open()) return "Failed to open file.";

  file.seekg(0, std::ios::end);
  std::streampos fileSize = file.tellg();

  if (fileSize == -1) {
    file.close();
    return "Failed to determine file size.";
  }

  file.seekg(0, std::ios::beg);

  std::vector<char> Data(static_cast<size_t>(fileSize));
  if (!file.read(Data.data(), fileSize)) {
    file.close();
    return "Failed to read.";
  }

  file.close();

  // Compression
  // W.I.P
  // int MaxLength = DataSize + 512 + (DataSize >> 2) + sizeof(int);
  // char *CompressedData = new char[MaxLength];
  // int CompressedSize = SomeCompression()
  // memset(CompressedData + CompressedSize, 0, MaxLength - CompressedSize);

  // Output
  std::ostringstream oss;
  oss << "#pragma once\n\n";
  oss << "/*\n";
  oss << " *\tGenerated by File To Byte\n";
  oss << " *\thttps://github.com/JerimiahOfficial/FileToByte\n";
  oss << " */\n\n";
  oss << "const unsigned int " << VarName << "_Size = " << fileSize << ";\n";
  oss << "const unsigned int " << VarName << "_Data[" << fileSize << "/4] = {";

  int Column = 0;
  for (size_t i = 0; i < static_cast<size_t>(fileSize); i++) {
    unsigned int D = static_cast<unsigned char>(Data[i]);

    if ((Column++ % 15) == 0) oss << "\t\n";
    if (i != static_cast<size_t>(fileSize) - 1)
      oss << "0x" << std::setw(2) << std::setfill('0') << std::hex << D << ", ";
    else
      oss << "0x" << std::setw(2) << std::setfill('0') << std::hex << D << "\n";
  }

  oss << "};\n";

  // Cleanup
  return oss.str();
}

}  // namespace FileToByte
